# Generated by Django 5.2.17 on 2026-08-18 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '__first__'),
        ('tables', '0003_remove_table_is_occupied_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.bill'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tables.table'),
        ),
    ]
