# Generated by Django 5.2.17 on 2026-08-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_bill_alter_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='notes',
            field=models.CharField(blank=True, default='', help_text='Ej. "sin cebolla", "bien cocido"', max_length=200, verbose_name='Notas'),
        ),
    ]
