# Generated by Django 5.2.17 on 2026-08-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Se exige cambiarla en el primer inicio de sesión (contraseña temporal).', verbose_name='Debe cambiar la contraseña'),
        ),
    ]
