# Generated by Django 5.2.17 on 2026-08-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Número')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Ocupada')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
