# Generated by Django 5.2.17 on 2026-08-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_seed_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_occupied',
        ),
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADA', 'Ocupada'), ('CUENTA_PEDIDA', 'Cuenta Pedida'), ('RESERVADA', 'Reservada'), ('LIMPIEZA', 'En Limpieza')], default='LIBRE', max_length=20, verbose_name='Estado'),
        ),
    ]
