---
- name: Actualizar cache de apt
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Instalar paquetes base
  ansible.builtin.apt:
    name:
      - curl
      - git
      - ufw
      - unzip
      - ca-certificates
      - gnupg
    state: present

- name: Configurar UFW - permitir SSH
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Configurar UFW - permitir HTTP/HTTPS
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "80"
    - "443"

- name: Activar UFW
  community.general.ufw:
    state: enabled
    policy: deny
