# Generated by Django 5.2.17 on 2026-08-29 17:08

import apps.attendance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('secret_key', models.CharField(default=apps.attendance.models._generate_secret, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kiosco',
                'verbose_name_plural': 'Kioscos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('token_used', models.CharField(max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prev_hash', models.CharField(blank=True, default='', max_length=64)),
                ('hash', models.CharField(editable=False, max_length=64)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='employees.employee')),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='attendance.kiosk')),
            ],
            options={
                'verbose_name': 'Marcación',
                'verbose_name_plural': 'Marcaciones',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('previous_timestamp', models.DateTimeField()),
                ('new_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prev_hash', models.CharField(blank=True, default='', max_length=64)),
                ('hash', models.CharField(editable=False, max_length=64)),
                ('adjusted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_adjustments_made', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='attendance.timeentry')),
            ],
            options={
                'verbose_name': 'Ajuste de marcación',
                'verbose_name_plural': 'Ajustes de marcación',
                'ordering': ['created_at'],
            },
        ),
    ]
