# Generated by Django 5.2.17 on 2026-08-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_append_only_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timeentryadjustment',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
