# Generated by Django 5.2.17 on 2026-08-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_shift_overtimerequest_shift_unique_shift_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosk',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Pantalla habilitada'),
        ),
    ]
