# Generated by Django 5.2.17 on 2026-08-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_kioskaccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskaccessrequest',
            name='session_key',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
