# Generated by Django 5.2.17 on 2026-08-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_seed_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='station',
            field=models.CharField(choices=[('COCINA', 'Cocina'), ('BAR', 'Bar')], default='COCINA', help_text='A qué pantalla de KDS se enrutan los productos de esta categoría.', max_length=20, verbose_name='Estación'),
        ),
    ]
