# Generated by Django 5.2.17 on 2026-08-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_bebidas_a_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Foto (enlace externo)'),
        ),
    ]
