# Generated by Django 5.2.17 on 2026-08-18 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('position', models.CharField(choices=[('GERENTE', 'Administrador / Gerente'), ('MESERO', 'Mesero'), ('COCINERO', 'Cocinero / Bartender'), ('CAJERO', 'Cajero'), ('HOSTESS', 'Hostess'), ('BODEGUERO', 'Bodeguero'), ('COMPRAS', 'Encargado de Compras'), ('REPARTIDOR', 'Repartidor')], max_length=20, verbose_name='Puesto')),
                ('hire_date', models.DateField(verbose_name='Fecha de contratación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
