# Generated by Django 5.2.17 on 2026-08-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('GERENTE', 'Administrador / Gerente'), ('MESERO', 'Mesero'), ('COCINERO', 'Cocinero'), ('BARTENDER', 'Bartender'), ('CAJERO', 'Cajero'), ('HOSTESS', 'Hostess'), ('BODEGUERO', 'Bodeguero'), ('COMPRAS', 'Encargado de Compras'), ('REPARTIDOR', 'Repartidor'), ('KIOSKO', 'Kiosko (pantalla de asistencia)')], max_length=20, verbose_name='Puesto'),
        ),
    ]
